### ISSUE TITLE
Any plan to implement or fix "current limitations"?

### ISSUE THREAD

**Issue by chris001** [inverse-inc/sogo#107]
Are these features to implement, more on the OpenChange side, or the Sogo side ?

http://www.sogo.nu/files/docs/SOGo%20Native%20Microsoft%20Outlook%20Configuration.pdf

General

  If  you  can't  see  any  email's  content  with  Microsoft  Outlook  2007,  install  the  latest  Service
Pack  available  from  Microsoft’s  website  for  this  specific  version.  Microsoft  Outlook  2007
(12.0.6423.100) SP2 MSO (12.0.6425.1000) is known to work.

  When you create a new Microsoft Outlook profile, not all folders might be synchronized during
the first start. Simply select the appropriate folder and click "Send and Receive". Synchronizing a
folder may take some time. For example, a folder with 1000 email messages might take around
5 minutes based on the underlying hardware.

  Errors when synchronizing the "Offline Address Book" are normal and can be ignored for now.
This feature is currently not supported.

  If you face strange issues from Microsoft Outlook, you might want to remove any data associated
with the user from the SOGo server and recreate a Microsoft Outlook profile. To remove any
data associated to a user, use the openchange_user_cleanup script distributed with SOGo. The
script can be found in /usr/share/doc/sogo/ (/usr/share/sogo-VERSION/ on RHEL). To reset
a user, run the script as root: openchange_user_cleanup username. See the usage output for
additional options.

  The "Out of Office Assistant" will not currently work. This feature has not been implemented.

  Creating folders below INBOX (when not normally permitted by the IMAP server), below the Personal
Calendar or Personal Address Book will work in Outlook cached mode but the server-side
operation will fail and these folders will never be created. Potentially data loss can occur if the
Outlook profile is destroyed. If you wan to create additional top-level mail folders, calendars or
address books, open Outlook’s folder list, select the top level node (usually, "email@example.com")
and choose "New Folder…" from the contextual menu. Choose the relevant item types.

Mail

  Sharing mail folders is not supported.

  To avoid possibly lossy conversion from RTF to HTML, Outlook should be configured to send all
mails as HTML (or plaintext) instead of Outlook Rich Text Format.
Calendar

  Labels will not work.

  It might be impossible to view event details from a shared calendar. This issue is being worked on.
Tasks

  Tasks with start/due dates created from Outlook might not appear correctly in SOGo due to a
timezone issue.

  Reminders are not yet supported.

  Assigning tasks will not work.

Contacts

  Categories will not work.

  Distribution lists will not work.

  Under Microsoft Outlook 2010, the special folder "Suggested Contacts" will not work.

  The "Offline Address Book" will not work. This feature is not yet supported.

Notes

  Notes are not synchronized in any ways with SOGo. The current version of SOGo lacks support
for notes.

**Comment by extrafu** [comment]
Yes we do indeed plan to fix these. It'll take time as some of them are not trivial.
