### ISSUE TITLE
Implement Gitter.Im?

### ISSUE THREAD

**Issue by lenucksi** [inverse-inc/sogo#122]
Hello,
as the SOGo IRC channel on FreeNode is rather silent and the development now appears to happen entirely on GitHub I wonder if you have considered integrating http://gitter.im for this repo.
It is a chat system (browser, apps, ...) integrated tightly with GitHub and its commits, pull request and issue system and various other systems if so chosen.
Also the integration is free of charge for you and its users.

**Comment by extrafu** [comment]
It's a good idea, bring it to the SOGo mailing list to see what others think.

**Comment by lenucksi** [comment]
Done.

**Comment by lenucksi** [comment]
Until now, nobody has voiced any concerns on the list. 
As this is not supposed to supersede the users list, I guess you could activate it on this repo then. They provide a feature that submits a pull request with a badge that links from the repos' readme to the Gitter-Channel.
