### ISSUE TITLE
Events (Chrome Linux) link does not work

### ISSUE THREAD

**Issue by whitx** [inverse-inc/sogo#140]
When you click a link in the event description, it does not redirect you to the site it try to add the url to https://sogo.inverse.ca/SOGo/so/aamacher/Calendar/,
ex: https://sogo.inverse.ca/SOGo/so/aamacher/Calendar/otbm.com

**Comment by cgx** [comment]
Fixed the edition by setting the input type to URL (fe6bd70b72c2138fb66649ef76b2aaf941d703b9).

**Comment by cgx** [comment]
Fixed by 8593ee9fbb31354a407defa4457f164cb9c3609b
