### ISSUE TITLE
Confusing placement of text box when searching for a shared folder (In chrome)

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/sogo#141]
In chrome clicking on 'Search User' icon does not allow you to search for a shared folder.

![image](https://cloud.githubusercontent.com/assets/2727473/11702120/0bb40306-9ea2-11e5-89ec-e556a8fa99d9.png)

**Comment by extrafu** [comment]
Most likely a bug in Angular Material at the time of testing. Retry and reopen if necessary.

**Comment by jrouzierinverse** [comment]
Looks good
