### ISSUE TITLE
Address Book (Chrome Android 5.1.1): Clicking on an address book doen't show it

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/sogo#143]
![screenshot_2015-12-09-18-29-12](https://cloud.githubusercontent.com/assets/1553962/11702214/ed46a5d0-9ea2-11e5-80cf-3584e2be975f.png)

**Comment by cgx** [comment]
Fixed by 80533a6f9a0f680fdf9fb2af3479285565b75339
