### ISSUE TITLE
Calendar — When creating an event, the URL-add button is labeled “Attach”

### ISSUE THREAD

**Issue by waptaff** [inverse-inc/sogo#160]
Firefox 38.4.0 (rebranded as Iceweasel) under Debian Jessie.

That's confusing.  See screenshot, left side:

![attach-url](https://cloud.githubusercontent.com/assets/6563434/11702870/2d382b14-9ea8-11e5-8c61-5e5046b8fefc.png)

**Comment by extrafu** [comment]
This mimics what we have in v2 and what is available in Lightning too. So right now this is fine.
