### ISSUE TITLE
Mailbox error message (Chrome Linux)

### ISSUE THREAD

**Issue by whitx** [inverse-inc/sogo#161]
While creating a folder in the mailbox, if for instance your name is too long (wild guess there)the error message is:

`An error occured while creating the mailbox "OMggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggdffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff".
The folder with name "OMggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggdffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff" could not be created.`

**Comment by extrafu** [comment]
"Normal" - there's a limit imposed by each IMAP server. In our case, Cyrus returns:

"NO System I/O error" so SOGo tells you that an error occured.

**Comment by whitx** [comment]
wondered if there is a way to improve this error message, "The name of the folder you created is too long" for instance.

**Comment by extrafu** [comment]
No really, since the I/O error can be for anything - lack of disk space, bad name, zammitiscurrentlyloggedin, etc.
