### ISSUE TITLE
Email (Chrome OS on Chromebook) - Signature for sub account is not applied

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/sogo#173]

**Comment by extrafu** [comment]
I guess you mean when you switch the "From" in the mail editor window?

If that's a known issue in v2 also, quite hard to fix.

**Comment by dwlfrth** [comment]
That's how I tested it yes

**Comment by extrafu** [comment]
Ok, I'll close this issue for now since the same issue is already in Mantis. Don't reopen it, or I'll break your  other arm!
