### ISSUE TITLE
Unstyled Warning when deleting a calendar

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/sogo#177]
When deleting a calendar, I get an unstyled warning in Safari 9.0.1.

![image](https://cloud.githubusercontent.com/assets/193997/11749286/ccb1d46c-9ffa-11e5-91e4-c8adcb22348f.png)

**Comment by extrafu** [comment]
By unstyled, you mean the <em> that isn't taken care of?

**Comment by louismunro** [comment]
I meant that the <em></em> tags are left as such in the the pop up.
The text is not empasized. 
I supposed it is styled, but the style is not applied.
