### ISSUE TITLE
Is normal to have so many activesync traffic?

### ISSUE THREAD

**Issue by alejandro-anv** [inverse-inc/sogo#179]
Using sogo-activesync-2.3.4-1.el7.centos.x86_64. with outlook 2013 client. Working OK but I see 2 things that does not look well:

1) At Apache and sogo logs I see many traffic with only one client. 
2) Most of the time the outlook 2013 client says "waiting for server response".

# tail -f /var/log/sogo/sogo.log

Dec 23 11:58:54 sogod [22823]: 192.168.0.202 "POST /SOGo/Microsoft-Server-ActiveSync?Cmd=Sync&User=anv@test.com&DeviceId=1BAB580EC03845059949D02CFFD3458E&DeviceType=WindowsOutlook15 HTTP/1.1" 200 0/399 0.936 - - -28K
Dec 23 11:58:54 sogod [22823]: 192.168.0.202 "POST /SOGo/Microsoft-Server-ActiveSync?Cmd=Ping&User=anv@test.com&DeviceId=1BAB580EC03845059949D02CFFD3458E&DeviceType=WindowsOutlook15 HTTP/1.1" 200 13/223 0.005 - - 0
Dec 23 11:58:55 sogod [22823]: 192.168.0.202 "POST /SOGo/Microsoft-Server-ActiveSync?Cmd=Sync&User=anv@test.com&DeviceId=1BAB580EC03845059949D02CFFD3458E&DeviceType=WindowsOutlook15 HTTP/1.1" 200 0/399 0.581 - - -40K
Dec 23 11:58:55 sogod [22823]: 192.168.0.202 "POST /SOGo/Microsoft-Server-ActiveSync?Cmd=Ping&User=anv@test.com&DeviceId=1BAB580EC03845059949D02CFFD3458E&DeviceType=WindowsOutlook15 HTTP/1.1" 200 13/223 0.006 - - 0
Dec 23 11:58:55 sogod [22823]: 192.168.0.202 "POST /SOGo/Microsoft-Server-ActiveSync?Cmd=Sync&User=anv@test.com&DeviceId=1BAB580EC03845059949D02CFFD3458E&DeviceType=WindowsOutlook15 HTTP/1.1" 200 0/399 0.891 - - -160K
Dec 23 11:58:56 sogod [22823]: 192.168.0.202 "POST /SOGo/Microsoft-Server-ActiveSync?Cmd=Ping&User=anv@test.com&DeviceId=1BAB580EC03845059949D02CFFD3458E&DeviceType=WindowsOutlook15 HTTP/1.1" 200 13/223 0.006 - - 0
Dec 23 11:58:56 sogod [22823]: 192.168.0.202 "POST /SOGo/Microsoft-Server-ActiveSync?Cmd=Sync&User=anv@test.com&DeviceId=1BAB580EC03845059949D02CFFD3458E&DeviceType=WindowsOutlook15 HTTP/1.1" 200 0/399 0.458 - - -12K
Dec 23 11:58:56 sogod [22823]: 192.168.0.202 "POST /SOGo/Microsoft-Server-ActiveSync?Cmd=Ping&User=anv@test.com&DeviceId=1BAB580EC03845059949D02CFFD3458E&DeviceType=WindowsOutlook15 HTTP/1.1" 200 13/223 0.005 - - 0
Dec 23 11:58:57 sogod [22823]: 192.168.0.202 "POST /SOGo/Microsoft-Server-ActiveSync?Cmd=Sync&User=anv@test.com&DeviceId=1BAB580EC03845059949D02CFFD3458E&DeviceType=WindowsOutlook15 HTTP/1.1" 200 0/399 0.782 - - -148K
Dec 23 11:58:57 sogod [22823]: 192.168.0.202 "POST /SOGo/Microsoft-Server-ActiveSync?Cmd=Ping&User=anv@test.com&DeviceId=1BAB580EC03845059949D02CFFD3458E&DeviceType=WindowsOutlook15 HTTP/1.1" 200 13/223 0.005 - - 0
Dec 23 11:58:58 sogod [22823]: 192.168.0.202 "POST /SOGo/Microsoft-Server-ActiveSync?Cmd=Sync&User=anv@test.com&DeviceId=1BAB580EC03845059949D02CFFD3458E&DeviceType=WindowsOutlook15 HTTP/1.1" 200 0/399 0.629 - - -156K
Dec 23 11:58:58 sogod [22823]: 192.168.0.202 "POST /SOGo/Microsoft-Server-ActiveSync?Cmd=Ping&User=anv@test.com&DeviceId=1BAB580EC03845059949D02CFFD3458E&DeviceType=WindowsOutlook15 HTTP/1.1" 200 13/223 0.008 - - 0
^C

**Comment by extrafu** [comment]
Use the mailing list.
