### ISSUE TITLE
ActiveSync - error 500

### ISSUE THREAD

**Issue by Peter2121** [inverse-inc/sogo#182]
Sogo 2.3.4 is installed inside FreeBSD jail. Anything works fine but ActiveSync.
There is an error 500 after GET /SOGo/Microsoft-Server-ActiveSync.
Nothing special in sogo.log:
Jan 13 14:19:46 sogod [3161]: 172.31.211.213 "GET /SOGo/Microsoft-Server-ActiveSync HTTP/1.0" 500 197/0 0.016 - - -

I put the traces in attached file (nothing special neither).
[export-sogo-async1.txt](https://github.com/inverse-inc/sogo/files/88910/export-sogo-async1.txt)

Is there any way to get more information about the problem?

**Comment by extrafu** [comment]
Which EAS client are you using? What is the libwbxml version?

**Comment by Peter2121** [comment]
ActiveSync Tester from https://store.accessmylan.com/main/diagnostic-tools
wbxml2-0.11.2

**Comment by extrafu** [comment]
Try with a real EAS client - testing tool can send bogus data and SOGo is known to work with all popular EAS clients. Bring this to sogo.nu/bugs as we are closing this BTS.
