### ISSUE TITLE
High memory usage on Debian Jessie

### ISSUE THREAD

**Issue by pschichtel** [inverse-inc/sogo#183]
I'm currently running SOGo on a single core Debian Wheezy (7.9) system with 2G of RAM.
This works fine without any problems.

However: After upgrading the System to Debian Jessie (8.2), SOGo suddenly starts to quickly eat up all of the memory including the Swap until it finally becomes unusable. This happens in a timespan of a few minutes.
This installation is only used by a few people and at the time of testing this issue I was always the only user.
I tried upgrading to Jessie with different 2.3.x releases all yielding the same problems until I revert back to Wheezy.

**Comment by extrafu** [comment]
Bring this to the mailing list, with evidences and details on your clients usage (DAV, EAS, etc.).
