### ISSUE TITLE
additional identities in a single account

### ISSUE THREAD

**Issue by wagnst** [inverse-inc/sogo#185]
Hi guys,

i am using a single account for different mail adresses (domains).
I am missing a big feature: Identities...

All other mail clients (Thunderbird, AquaMail, Horde) support this feature. I simply want to add a identity somewhere in settings and be able to select this identiy from dropdown in a mail sending dialogue.

Is this already implemented and i am only blind? Or is it missing?

Thanks + kind regards,
Steffen

**Comment by extrafu** [comment]
See http://sogo.nu/bugs/view.php?id=768 - move the discussion over there as we are closing the BTS on github as we will keep using Mantis.

**Comment by wagnst** [comment]
I have +1 this one already but no answer :-(
i miss this feature really "hard"...
